// Code generated by protoc-gen-go. DO NOT EDIT.
// source: study.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StudyMetaData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate            int64    `protobuf:"varint,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Users                []string `protobuf:"bytes,6,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudyMetaData) Reset()         { *m = StudyMetaData{} }
func (m *StudyMetaData) String() string { return proto.CompactTextString(m) }
func (*StudyMetaData) ProtoMessage()    {}
func (*StudyMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{0}
}

func (m *StudyMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyMetaData.Unmarshal(m, b)
}
func (m *StudyMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyMetaData.Marshal(b, m, deterministic)
}
func (m *StudyMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyMetaData.Merge(m, src)
}
func (m *StudyMetaData) XXX_Size() int {
	return xxx_messageInfo_StudyMetaData.Size(m)
}
func (m *StudyMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_StudyMetaData proto.InternalMessageInfo

func (m *StudyMetaData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StudyMetaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudyMetaData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StudyMetaData) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *StudyMetaData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StudyMetaData) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type StudyUsers struct {
	Users                []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudyUsers) Reset()         { *m = StudyUsers{} }
func (m *StudyUsers) String() string { return proto.CompactTextString(m) }
func (*StudyUsers) ProtoMessage()    {}
func (*StudyUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{1}
}

func (m *StudyUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyUsers.Unmarshal(m, b)
}
func (m *StudyUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyUsers.Marshal(b, m, deterministic)
}
func (m *StudyUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyUsers.Merge(m, src)
}
func (m *StudyUsers) XXX_Size() int {
	return xxx_messageInfo_StudyUsers.Size(m)
}
func (m *StudyUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyUsers.DiscardUnknown(m)
}

var xxx_messageInfo_StudyUsers proto.InternalMessageInfo

func (m *StudyUsers) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StudyArray struct {
	Studies              []*StudyMetaData `protobuf:"bytes,1,rep,name=studies,proto3" json:"studies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StudyArray) Reset()         { *m = StudyArray{} }
func (m *StudyArray) String() string { return proto.CompactTextString(m) }
func (*StudyArray) ProtoMessage()    {}
func (*StudyArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{3}
}

func (m *StudyArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyArray.Unmarshal(m, b)
}
func (m *StudyArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyArray.Marshal(b, m, deterministic)
}
func (m *StudyArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyArray.Merge(m, src)
}
func (m *StudyArray) XXX_Size() int {
	return xxx_messageInfo_StudyArray.Size(m)
}
func (m *StudyArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyArray.DiscardUnknown(m)
}

var xxx_messageInfo_StudyArray proto.InternalMessageInfo

func (m *StudyArray) GetStudies() []*StudyMetaData {
	if m != nil {
		return m.Studies
	}
	return nil
}

type StudyID struct {
	StudyID              string   `protobuf:"bytes,1,opt,name=studyID,proto3" json:"studyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudyID) Reset()         { *m = StudyID{} }
func (m *StudyID) String() string { return proto.CompactTextString(m) }
func (*StudyID) ProtoMessage()    {}
func (*StudyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{4}
}

func (m *StudyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudyID.Unmarshal(m, b)
}
func (m *StudyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudyID.Marshal(b, m, deterministic)
}
func (m *StudyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudyID.Merge(m, src)
}
func (m *StudyID) XXX_Size() int {
	return xxx_messageInfo_StudyID.Size(m)
}
func (m *StudyID) XXX_DiscardUnknown() {
	xxx_messageInfo_StudyID.DiscardUnknown(m)
}

var xxx_messageInfo_StudyID proto.InternalMessageInfo

func (m *StudyID) GetStudyID() string {
	if m != nil {
		return m.StudyID
	}
	return ""
}

type UserAssignment struct {
	StudyID              string   `protobuf:"bytes,1,opt,name=studyID,proto3" json:"studyID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAssignment) Reset()         { *m = UserAssignment{} }
func (m *UserAssignment) String() string { return proto.CompactTextString(m) }
func (*UserAssignment) ProtoMessage()    {}
func (*UserAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{5}
}

func (m *UserAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAssignment.Unmarshal(m, b)
}
func (m *UserAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAssignment.Marshal(b, m, deterministic)
}
func (m *UserAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAssignment.Merge(m, src)
}
func (m *UserAssignment) XXX_Size() int {
	return xxx_messageInfo_UserAssignment.Size(m)
}
func (m *UserAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_UserAssignment proto.InternalMessageInfo

func (m *UserAssignment) GetStudyID() string {
	if m != nil {
		return m.StudyID
	}
	return ""
}

func (m *UserAssignment) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*StudyMetaData)(nil), "api.StudyMetaData")
	proto.RegisterType((*StudyUsers)(nil), "api.StudyUsers")
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*StudyArray)(nil), "api.StudyArray")
	proto.RegisterType((*StudyID)(nil), "api.StudyID")
	proto.RegisterType((*UserAssignment)(nil), "api.UserAssignment")
}

func init() { proto.RegisterFile("study.proto", fileDescriptor_b59e246e4c4c09f0) }

var fileDescriptor_b59e246e4c4c09f0 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x25, 0x49, 0x93, 0xbe, 0xde, 0xbc, 0xd7, 0x87, 0x57, 0x91, 0x50, 0x5c, 0x84, 0x88, 0x58,
	0xa1, 0x74, 0x51, 0xe9, 0x46, 0xdc, 0x54, 0x23, 0x25, 0x0b, 0x37, 0xd1, 0x7e, 0xc0, 0x68, 0x06,
	0x19, 0x68, 0x93, 0x90, 0xb9, 0x5d, 0xe4, 0x73, 0xfc, 0x2f, 0x3f, 0x46, 0x66, 0x26, 0x25, 0x29,
	0xc4, 0x85, 0xbb, 0x9c, 0x7b, 0xcf, 0x99, 0x7b, 0xce, 0x21, 0xe0, 0x4b, 0xda, 0x67, 0xf5, 0xbc,
	0xac, 0x0a, 0x2a, 0xd0, 0x61, 0xa5, 0x88, 0x3e, 0x2d, 0xf8, 0xf7, 0xa2, 0x86, 0xcf, 0x9c, 0x58,
	0xcc, 0x88, 0xe1, 0x18, 0x6c, 0x91, 0x05, 0x56, 0x68, 0x4d, 0x47, 0xa9, 0x2d, 0x32, 0x44, 0x18,
	0xe4, 0x6c, 0xc7, 0x03, 0x5b, 0x4f, 0xf4, 0x37, 0x86, 0xe0, 0x67, 0x5c, 0xbe, 0x57, 0xa2, 0x24,
	0x51, 0xe4, 0x81, 0xa3, 0x57, 0xdd, 0x11, 0x5e, 0xc0, 0x48, 0x12, 0xab, 0x28, 0x66, 0xc4, 0x83,
	0x41, 0x68, 0x4d, 0x9d, 0xb4, 0x1d, 0xe0, 0x39, 0x78, 0x92, 0x18, 0xed, 0x65, 0xe0, 0x6a, 0x69,
	0x83, 0xf0, 0x0c, 0xdc, 0xbd, 0xe4, 0x95, 0x0c, 0xbc, 0xd0, 0x99, 0x8e, 0x52, 0x03, 0xa2, 0x08,
	0x40, 0x5b, 0xdc, 0x28, 0xd4, 0x72, 0xac, 0x2e, 0x67, 0x08, 0xee, 0xd3, 0xae, 0xa4, 0x3a, 0xba,
	0x6b, 0xc8, 0xab, 0xaa, 0x62, 0x35, 0xce, 0x60, 0xa8, 0x22, 0x0b, 0x6e, 0xe8, 0xfe, 0x02, 0xe7,
	0xac, 0x14, 0xf3, 0xa3, 0xc4, 0xe9, 0x81, 0x12, 0x5d, 0xc2, 0x50, 0x6f, 0x92, 0x18, 0x03, 0x23,
	0xac, 0x93, 0xb8, 0xa9, 0xe2, 0x00, 0xa3, 0x07, 0x18, 0x2b, 0x23, 0x2b, 0x29, 0xc5, 0x47, 0xbe,
	0xe3, 0x39, 0xfd, 0xcc, 0x55, 0x39, 0x95, 0xbd, 0x24, 0x6e, 0xda, 0x6b, 0xd0, 0xe2, 0xcb, 0x06,
	0x57, 0x5f, 0xc2, 0x1b, 0xf8, 0xb3, 0xe6, 0x64, 0x92, 0xfd, 0x6d, 0xbd, 0x25, 0xf1, 0xe4, 0x7f,
	0x8b, 0xcc, 0x7a, 0x09, 0xfe, 0x63, 0xc5, 0x19, 0x71, 0xa3, 0xec, 0x49, 0x32, 0xe9, 0x99, 0xe1,
	0x3d, 0x9c, 0x18, 0xaf, 0xea, 0x95, 0xd7, 0xc2, 0x88, 0x4f, 0x35, 0xf1, 0x38, 0x47, 0xaf, 0xfa,
	0x0a, 0xbc, 0x35, 0xa7, 0xd5, 0x76, 0x8b, 0xa0, 0xb7, 0xba, 0xe4, 0xae, 0x37, 0xd3, 0xf3, 0x12,
	0xfc, 0x4d, 0x99, 0xfd, 0xda, 0xdb, 0x35, 0xf8, 0x31, 0xdf, 0xf2, 0x83, 0xec, 0xb8, 0x80, 0xce,
	0x41, 0x9c, 0xe9, 0x9a, 0xfa, 0x58, 0x3d, 0xcf, 0xbe, 0x79, 0xfa, 0x07, 0xbf, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x63, 0xd5, 0xb8, 0x3e, 0xef, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudyClient is the client API for Study service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudyClient interface {
	GetUsers(ctx context.Context, in *StudyID, opts ...grpc.CallOption) (*StudyUsers, error)
	CreateStudy(ctx context.Context, in *StudyMetaData, opts ...grpc.CallOption) (*StudyMetaData, error)
	AssignUserToStudy(ctx context.Context, in *UserAssignment, opts ...grpc.CallOption) (*StudyMetaData, error)
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StudyArray, error)
	UpdateStudy(ctx context.Context, in *StudyMetaData, opts ...grpc.CallOption) (*StudyMetaData, error)
	DeleteStudy(ctx context.Context, in *StudyID, opts ...grpc.CallOption) (*Empty, error)
	GetStudy(ctx context.Context, in *StudyID, opts ...grpc.CallOption) (*StudyMetaData, error)
}

type studyClient struct {
	cc *grpc.ClientConn
}

func NewStudyClient(cc *grpc.ClientConn) StudyClient {
	return &studyClient{cc}
}

func (c *studyClient) GetUsers(ctx context.Context, in *StudyID, opts ...grpc.CallOption) (*StudyUsers, error) {
	out := new(StudyUsers)
	err := c.cc.Invoke(ctx, "/api.Study/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyClient) CreateStudy(ctx context.Context, in *StudyMetaData, opts ...grpc.CallOption) (*StudyMetaData, error) {
	out := new(StudyMetaData)
	err := c.cc.Invoke(ctx, "/api.Study/CreateStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyClient) AssignUserToStudy(ctx context.Context, in *UserAssignment, opts ...grpc.CallOption) (*StudyMetaData, error) {
	out := new(StudyMetaData)
	err := c.cc.Invoke(ctx, "/api.Study/AssignUserToStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StudyArray, error) {
	out := new(StudyArray)
	err := c.cc.Invoke(ctx, "/api.Study/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyClient) UpdateStudy(ctx context.Context, in *StudyMetaData, opts ...grpc.CallOption) (*StudyMetaData, error) {
	out := new(StudyMetaData)
	err := c.cc.Invoke(ctx, "/api.Study/UpdateStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyClient) DeleteStudy(ctx context.Context, in *StudyID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Study/DeleteStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyClient) GetStudy(ctx context.Context, in *StudyID, opts ...grpc.CallOption) (*StudyMetaData, error) {
	out := new(StudyMetaData)
	err := c.cc.Invoke(ctx, "/api.Study/GetStudy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyServer is the server API for Study service.
type StudyServer interface {
	GetUsers(context.Context, *StudyID) (*StudyUsers, error)
	CreateStudy(context.Context, *StudyMetaData) (*StudyMetaData, error)
	AssignUserToStudy(context.Context, *UserAssignment) (*StudyMetaData, error)
	GetAll(context.Context, *Empty) (*StudyArray, error)
	UpdateStudy(context.Context, *StudyMetaData) (*StudyMetaData, error)
	DeleteStudy(context.Context, *StudyID) (*Empty, error)
	GetStudy(context.Context, *StudyID) (*StudyMetaData, error)
}

// UnimplementedStudyServer can be embedded to have forward compatible implementations.
type UnimplementedStudyServer struct {
}

func (*UnimplementedStudyServer) GetUsers(ctx context.Context, req *StudyID) (*StudyUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedStudyServer) CreateStudy(ctx context.Context, req *StudyMetaData) (*StudyMetaData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudy not implemented")
}
func (*UnimplementedStudyServer) AssignUserToStudy(ctx context.Context, req *UserAssignment) (*StudyMetaData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignUserToStudy not implemented")
}
func (*UnimplementedStudyServer) GetAll(ctx context.Context, req *Empty) (*StudyArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedStudyServer) UpdateStudy(ctx context.Context, req *StudyMetaData) (*StudyMetaData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudy not implemented")
}
func (*UnimplementedStudyServer) DeleteStudy(ctx context.Context, req *StudyID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudy not implemented")
}
func (*UnimplementedStudyServer) GetStudy(ctx context.Context, req *StudyID) (*StudyMetaData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudy not implemented")
}

func RegisterStudyServer(s *grpc.Server, srv StudyServer) {
	s.RegisterService(&_Study_serviceDesc, srv)
}

func _Study_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).GetUsers(ctx, req.(*StudyID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Study_CreateStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyMetaData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).CreateStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/CreateStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).CreateStudy(ctx, req.(*StudyMetaData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Study_AssignUserToStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAssignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).AssignUserToStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/AssignUserToStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).AssignUserToStudy(ctx, req.(*UserAssignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Study_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Study_UpdateStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyMetaData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).UpdateStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/UpdateStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).UpdateStudy(ctx, req.(*StudyMetaData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Study_DeleteStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).DeleteStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/DeleteStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).DeleteStudy(ctx, req.(*StudyID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Study_GetStudy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServer).GetStudy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Study/GetStudy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServer).GetStudy(ctx, req.(*StudyID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Study_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Study",
	HandlerType: (*StudyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _Study_GetUsers_Handler,
		},
		{
			MethodName: "CreateStudy",
			Handler:    _Study_CreateStudy_Handler,
		},
		{
			MethodName: "AssignUserToStudy",
			Handler:    _Study_AssignUserToStudy_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Study_GetAll_Handler,
		},
		{
			MethodName: "UpdateStudy",
			Handler:    _Study_UpdateStudy_Handler,
		},
		{
			MethodName: "DeleteStudy",
			Handler:    _Study_DeleteStudy_Handler,
		},
		{
			MethodName: "GetStudy",
			Handler:    _Study_GetStudy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "study.proto",
}
