// Code generated by protoc-gen-go. DO NOT EDIT.
// source: survey.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Id                   string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string                         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	QuestionWithLanguage *Question_QuestionWithLanguage `protobuf:"bytes,4,opt,name=questionWithLanguage,proto3" json:"questionWithLanguage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Question) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Question) GetQuestionWithLanguage() *Question_QuestionWithLanguage {
	if m != nil {
		return m.QuestionWithLanguage
	}
	return nil
}

type Question_AnswerOptions struct {
	OpenOptions          *Question_OpenOptions     `protobuf:"bytes,1,opt,name=openOptions,proto3" json:"openOptions,omitempty"`
	SingleOption         *Question_SingleOption    `protobuf:"bytes,2,opt,name=singleOption,proto3" json:"singleOption,omitempty"`
	MultipleOptions      *Question_MultipleOptions `protobuf:"bytes,3,opt,name=multipleOptions,proto3" json:"multipleOptions,omitempty"`
	MatrixOptions        []*Question_MatrixOptions `protobuf:"bytes,4,rep,name=matrixOptions,proto3" json:"matrixOptions,omitempty"`
	HideQuestion         []*Question_HideQuestion  `protobuf:"bytes,5,rep,name=hideQuestion,proto3" json:"hideQuestion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Question_AnswerOptions) Reset()         { *m = Question_AnswerOptions{} }
func (m *Question_AnswerOptions) String() string { return proto.CompactTextString(m) }
func (*Question_AnswerOptions) ProtoMessage()    {}
func (*Question_AnswerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 0}
}

func (m *Question_AnswerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_AnswerOptions.Unmarshal(m, b)
}
func (m *Question_AnswerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_AnswerOptions.Marshal(b, m, deterministic)
}
func (m *Question_AnswerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_AnswerOptions.Merge(m, src)
}
func (m *Question_AnswerOptions) XXX_Size() int {
	return xxx_messageInfo_Question_AnswerOptions.Size(m)
}
func (m *Question_AnswerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_AnswerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Question_AnswerOptions proto.InternalMessageInfo

func (m *Question_AnswerOptions) GetOpenOptions() *Question_OpenOptions {
	if m != nil {
		return m.OpenOptions
	}
	return nil
}

func (m *Question_AnswerOptions) GetSingleOption() *Question_SingleOption {
	if m != nil {
		return m.SingleOption
	}
	return nil
}

func (m *Question_AnswerOptions) GetMultipleOptions() *Question_MultipleOptions {
	if m != nil {
		return m.MultipleOptions
	}
	return nil
}

func (m *Question_AnswerOptions) GetMatrixOptions() []*Question_MatrixOptions {
	if m != nil {
		return m.MatrixOptions
	}
	return nil
}

func (m *Question_AnswerOptions) GetHideQuestion() []*Question_HideQuestion {
	if m != nil {
		return m.HideQuestion
	}
	return nil
}

type Question_OpenOptions struct {
	DataType             string   `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	OpenAnswer           string   `protobuf:"bytes,2,opt,name=openAnswer,proto3" json:"openAnswer,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question_OpenOptions) Reset()         { *m = Question_OpenOptions{} }
func (m *Question_OpenOptions) String() string { return proto.CompactTextString(m) }
func (*Question_OpenOptions) ProtoMessage()    {}
func (*Question_OpenOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 1}
}

func (m *Question_OpenOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_OpenOptions.Unmarshal(m, b)
}
func (m *Question_OpenOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_OpenOptions.Marshal(b, m, deterministic)
}
func (m *Question_OpenOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_OpenOptions.Merge(m, src)
}
func (m *Question_OpenOptions) XXX_Size() int {
	return xxx_messageInfo_Question_OpenOptions.Size(m)
}
func (m *Question_OpenOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_OpenOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Question_OpenOptions proto.InternalMessageInfo

func (m *Question_OpenOptions) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Question_OpenOptions) GetOpenAnswer() string {
	if m != nil {
		return m.OpenAnswer
	}
	return ""
}

func (m *Question_OpenOptions) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Question_Options struct {
	OptionText           []string `protobuf:"bytes,1,rep,name=optionText,proto3" json:"optionText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question_Options) Reset()         { *m = Question_Options{} }
func (m *Question_Options) String() string { return proto.CompactTextString(m) }
func (*Question_Options) ProtoMessage()    {}
func (*Question_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 2}
}

func (m *Question_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_Options.Unmarshal(m, b)
}
func (m *Question_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_Options.Marshal(b, m, deterministic)
}
func (m *Question_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_Options.Merge(m, src)
}
func (m *Question_Options) XXX_Size() int {
	return xxx_messageInfo_Question_Options.Size(m)
}
func (m *Question_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Question_Options proto.InternalMessageInfo

func (m *Question_Options) GetOptionText() []string {
	if m != nil {
		return m.OptionText
	}
	return nil
}

type Question_SingleOption struct {
	Options              map[string]*Question_Options `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SelectedOption       string                       `protobuf:"bytes,2,opt,name=selectedOption,proto3" json:"selectedOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Question_SingleOption) Reset()         { *m = Question_SingleOption{} }
func (m *Question_SingleOption) String() string { return proto.CompactTextString(m) }
func (*Question_SingleOption) ProtoMessage()    {}
func (*Question_SingleOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 3}
}

func (m *Question_SingleOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_SingleOption.Unmarshal(m, b)
}
func (m *Question_SingleOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_SingleOption.Marshal(b, m, deterministic)
}
func (m *Question_SingleOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_SingleOption.Merge(m, src)
}
func (m *Question_SingleOption) XXX_Size() int {
	return xxx_messageInfo_Question_SingleOption.Size(m)
}
func (m *Question_SingleOption) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_SingleOption.DiscardUnknown(m)
}

var xxx_messageInfo_Question_SingleOption proto.InternalMessageInfo

func (m *Question_SingleOption) GetOptions() map[string]*Question_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Question_SingleOption) GetSelectedOption() string {
	if m != nil {
		return m.SelectedOption
	}
	return ""
}

type Question_MultipleOptions struct {
	Options              map[string]*Question_Options `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SelectedOptions      []string                     `protobuf:"bytes,2,rep,name=selectedOptions,proto3" json:"selectedOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Question_MultipleOptions) Reset()         { *m = Question_MultipleOptions{} }
func (m *Question_MultipleOptions) String() string { return proto.CompactTextString(m) }
func (*Question_MultipleOptions) ProtoMessage()    {}
func (*Question_MultipleOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 4}
}

func (m *Question_MultipleOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_MultipleOptions.Unmarshal(m, b)
}
func (m *Question_MultipleOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_MultipleOptions.Marshal(b, m, deterministic)
}
func (m *Question_MultipleOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_MultipleOptions.Merge(m, src)
}
func (m *Question_MultipleOptions) XXX_Size() int {
	return xxx_messageInfo_Question_MultipleOptions.Size(m)
}
func (m *Question_MultipleOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_MultipleOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Question_MultipleOptions proto.InternalMessageInfo

func (m *Question_MultipleOptions) GetOptions() map[string]*Question_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Question_MultipleOptions) GetSelectedOptions() []string {
	if m != nil {
		return m.SelectedOptions
	}
	return nil
}

type Question_MatrixOptions struct {
	Text                 map[string]string            `protobuf:"bytes,1,rep,name=text,proto3" json:"text,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Options              map[string]*Question_Options `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SelectedOption       string                       `protobuf:"bytes,3,opt,name=selectedOption,proto3" json:"selectedOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Question_MatrixOptions) Reset()         { *m = Question_MatrixOptions{} }
func (m *Question_MatrixOptions) String() string { return proto.CompactTextString(m) }
func (*Question_MatrixOptions) ProtoMessage()    {}
func (*Question_MatrixOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 5}
}

func (m *Question_MatrixOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_MatrixOptions.Unmarshal(m, b)
}
func (m *Question_MatrixOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_MatrixOptions.Marshal(b, m, deterministic)
}
func (m *Question_MatrixOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_MatrixOptions.Merge(m, src)
}
func (m *Question_MatrixOptions) XXX_Size() int {
	return xxx_messageInfo_Question_MatrixOptions.Size(m)
}
func (m *Question_MatrixOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_MatrixOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Question_MatrixOptions proto.InternalMessageInfo

func (m *Question_MatrixOptions) GetText() map[string]string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Question_MatrixOptions) GetOptions() map[string]*Question_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Question_MatrixOptions) GetSelectedOption() string {
	if m != nil {
		return m.SelectedOption
	}
	return ""
}

type Question_HideQuestion struct {
	SelectedOption       string   `protobuf:"bytes,1,opt,name=selectedOption,proto3" json:"selectedOption,omitempty"`
	Question             string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question_HideQuestion) Reset()         { *m = Question_HideQuestion{} }
func (m *Question_HideQuestion) String() string { return proto.CompactTextString(m) }
func (*Question_HideQuestion) ProtoMessage()    {}
func (*Question_HideQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 6}
}

func (m *Question_HideQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_HideQuestion.Unmarshal(m, b)
}
func (m *Question_HideQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_HideQuestion.Marshal(b, m, deterministic)
}
func (m *Question_HideQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_HideQuestion.Merge(m, src)
}
func (m *Question_HideQuestion) XXX_Size() int {
	return xxx_messageInfo_Question_HideQuestion.Size(m)
}
func (m *Question_HideQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_HideQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_Question_HideQuestion proto.InternalMessageInfo

func (m *Question_HideQuestion) GetSelectedOption() string {
	if m != nil {
		return m.SelectedOption
	}
	return ""
}

func (m *Question_HideQuestion) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

type Question_QuestionWithLanguage struct {
	Text                 map[string]string       `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Image                map[string][]byte       `protobuf:"bytes,3,rep,name=image,proto3" json:"image,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AnswerOptions        *Question_AnswerOptions `protobuf:"bytes,4,opt,name=answerOptions,proto3" json:"answerOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Question_QuestionWithLanguage) Reset()         { *m = Question_QuestionWithLanguage{} }
func (m *Question_QuestionWithLanguage) String() string { return proto.CompactTextString(m) }
func (*Question_QuestionWithLanguage) ProtoMessage()    {}
func (*Question_QuestionWithLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0, 7}
}

func (m *Question_QuestionWithLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question_QuestionWithLanguage.Unmarshal(m, b)
}
func (m *Question_QuestionWithLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question_QuestionWithLanguage.Marshal(b, m, deterministic)
}
func (m *Question_QuestionWithLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question_QuestionWithLanguage.Merge(m, src)
}
func (m *Question_QuestionWithLanguage) XXX_Size() int {
	return xxx_messageInfo_Question_QuestionWithLanguage.Size(m)
}
func (m *Question_QuestionWithLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_Question_QuestionWithLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_Question_QuestionWithLanguage proto.InternalMessageInfo

func (m *Question_QuestionWithLanguage) GetText() map[string]string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Question_QuestionWithLanguage) GetImage() map[string][]byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Question_QuestionWithLanguage) GetAnswerOptions() *Question_AnswerOptions {
	if m != nil {
		return m.AnswerOptions
	}
	return nil
}

type QuestionID struct {
	QuestionID           string   `protobuf:"bytes,1,opt,name=questionID,proto3" json:"questionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionID) Reset()         { *m = QuestionID{} }
func (m *QuestionID) String() string { return proto.CompactTextString(m) }
func (*QuestionID) ProtoMessage()    {}
func (*QuestionID) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{1}
}

func (m *QuestionID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionID.Unmarshal(m, b)
}
func (m *QuestionID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionID.Marshal(b, m, deterministic)
}
func (m *QuestionID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionID.Merge(m, src)
}
func (m *QuestionID) XXX_Size() int {
	return xxx_messageInfo_QuestionID.Size(m)
}
func (m *QuestionID) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionID.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionID proto.InternalMessageInfo

func (m *QuestionID) GetQuestionID() string {
	if m != nil {
		return m.QuestionID
	}
	return ""
}

type SurveyID struct {
	SurveyID             string   `protobuf:"bytes,1,opt,name=surveyID,proto3" json:"surveyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurveyID) Reset()         { *m = SurveyID{} }
func (m *SurveyID) String() string { return proto.CompactTextString(m) }
func (*SurveyID) ProtoMessage()    {}
func (*SurveyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{2}
}

func (m *SurveyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyID.Unmarshal(m, b)
}
func (m *SurveyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyID.Marshal(b, m, deterministic)
}
func (m *SurveyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyID.Merge(m, src)
}
func (m *SurveyID) XXX_Size() int {
	return xxx_messageInfo_SurveyID.Size(m)
}
func (m *SurveyID) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyID.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyID proto.InternalMessageInfo

func (m *SurveyID) GetSurveyID() string {
	if m != nil {
		return m.SurveyID
	}
	return ""
}

type QuestionArray struct {
	Questions            []*Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuestionArray) Reset()         { *m = QuestionArray{} }
func (m *QuestionArray) String() string { return proto.CompactTextString(m) }
func (*QuestionArray) ProtoMessage()    {}
func (*QuestionArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{3}
}

func (m *QuestionArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionArray.Unmarshal(m, b)
}
func (m *QuestionArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionArray.Marshal(b, m, deterministic)
}
func (m *QuestionArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionArray.Merge(m, src)
}
func (m *QuestionArray) XXX_Size() int {
	return xxx_messageInfo_QuestionArray.Size(m)
}
func (m *QuestionArray) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionArray.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionArray proto.InternalMessageInfo

func (m *QuestionArray) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type SurveyArray struct {
	Surveys              []*SurveyData `protobuf:"bytes,1,rep,name=surveys,proto3" json:"surveys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SurveyArray) Reset()         { *m = SurveyArray{} }
func (m *SurveyArray) String() string { return proto.CompactTextString(m) }
func (*SurveyArray) ProtoMessage()    {}
func (*SurveyArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{4}
}

func (m *SurveyArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyArray.Unmarshal(m, b)
}
func (m *SurveyArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyArray.Marshal(b, m, deterministic)
}
func (m *SurveyArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyArray.Merge(m, src)
}
func (m *SurveyArray) XXX_Size() int {
	return xxx_messageInfo_SurveyArray.Size(m)
}
func (m *SurveyArray) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyArray.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyArray proto.InternalMessageInfo

func (m *SurveyArray) GetSurveys() []*SurveyData {
	if m != nil {
		return m.Surveys
	}
	return nil
}

type EmptySurvey struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptySurvey) Reset()         { *m = EmptySurvey{} }
func (m *EmptySurvey) String() string { return proto.CompactTextString(m) }
func (*EmptySurvey) ProtoMessage()    {}
func (*EmptySurvey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{5}
}

func (m *EmptySurvey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptySurvey.Unmarshal(m, b)
}
func (m *EmptySurvey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptySurvey.Marshal(b, m, deterministic)
}
func (m *EmptySurvey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptySurvey.Merge(m, src)
}
func (m *EmptySurvey) XXX_Size() int {
	return xxx_messageInfo_EmptySurvey.Size(m)
}
func (m *EmptySurvey) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptySurvey.DiscardUnknown(m)
}

var xxx_messageInfo_EmptySurvey proto.InternalMessageInfo

type SurveyData struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Study                string      `protobuf:"bytes,4,opt,name=study,proto3" json:"study,omitempty"`
	Questions            []*Question `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SurveyData) Reset()         { *m = SurveyData{} }
func (m *SurveyData) String() string { return proto.CompactTextString(m) }
func (*SurveyData) ProtoMessage()    {}
func (*SurveyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{6}
}

func (m *SurveyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyData.Unmarshal(m, b)
}
func (m *SurveyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyData.Marshal(b, m, deterministic)
}
func (m *SurveyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyData.Merge(m, src)
}
func (m *SurveyData) XXX_Size() int {
	return xxx_messageInfo_SurveyData.Size(m)
}
func (m *SurveyData) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyData.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyData proto.InternalMessageInfo

func (m *SurveyData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SurveyData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SurveyData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SurveyData) GetStudy() string {
	if m != nil {
		return m.Study
	}
	return ""
}

func (m *SurveyData) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

func init() {
	proto.RegisterType((*Question)(nil), "api.Question")
	proto.RegisterType((*Question_AnswerOptions)(nil), "api.Question.AnswerOptions")
	proto.RegisterType((*Question_OpenOptions)(nil), "api.Question.OpenOptions")
	proto.RegisterType((*Question_Options)(nil), "api.Question.Options")
	proto.RegisterType((*Question_SingleOption)(nil), "api.Question.SingleOption")
	proto.RegisterMapType((map[string]*Question_Options)(nil), "api.Question.SingleOption.OptionsEntry")
	proto.RegisterType((*Question_MultipleOptions)(nil), "api.Question.MultipleOptions")
	proto.RegisterMapType((map[string]*Question_Options)(nil), "api.Question.MultipleOptions.OptionsEntry")
	proto.RegisterType((*Question_MatrixOptions)(nil), "api.Question.MatrixOptions")
	proto.RegisterMapType((map[string]*Question_Options)(nil), "api.Question.MatrixOptions.OptionsEntry")
	proto.RegisterMapType((map[string]string)(nil), "api.Question.MatrixOptions.TextEntry")
	proto.RegisterType((*Question_HideQuestion)(nil), "api.Question.HideQuestion")
	proto.RegisterType((*Question_QuestionWithLanguage)(nil), "api.Question.QuestionWithLanguage")
	proto.RegisterMapType((map[string][]byte)(nil), "api.Question.QuestionWithLanguage.ImageEntry")
	proto.RegisterMapType((map[string]string)(nil), "api.Question.QuestionWithLanguage.TextEntry")
	proto.RegisterType((*QuestionID)(nil), "api.QuestionID")
	proto.RegisterType((*SurveyID)(nil), "api.SurveyID")
	proto.RegisterType((*QuestionArray)(nil), "api.QuestionArray")
	proto.RegisterType((*SurveyArray)(nil), "api.SurveyArray")
	proto.RegisterType((*EmptySurvey)(nil), "api.EmptySurvey")
	proto.RegisterType((*SurveyData)(nil), "api.SurveyData")
}

func init() { proto.RegisterFile("survey.proto", fileDescriptor_a40f94eaa8e6ca46) }

var fileDescriptor_a40f94eaa8e6ca46 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x55, 0x92, 0xe6, 0xb7, 0xf5, 0xa6, 0x5d, 0x7f, 0xb2, 0x8a, 0x14, 0x82, 0x40, 0x55, 0x24,
	0x46, 0x07, 0xa3, 0x0f, 0xe5, 0x81, 0xf1, 0x47, 0x88, 0x42, 0x27, 0x98, 0x04, 0x9a, 0xe6, 0x4d,
	0xf0, 0x88, 0xc2, 0x62, 0x6d, 0x16, 0xfd, 0x93, 0x25, 0xee, 0x58, 0x5f, 0xf9, 0x0e, 0x7c, 0x21,
	0x9e, 0x79, 0x83, 0x07, 0x3e, 0x0e, 0xb2, 0x1d, 0xa7, 0x76, 0x96, 0x75, 0x13, 0xd2, 0xde, 0xec,
	0x9b, 0x73, 0x8e, 0x7d, 0xef, 0xb9, 0xb9, 0x09, 0x34, 0xb2, 0x59, 0x7a, 0x4a, 0xe6, 0xbd, 0x24,
	0x9d, 0xb2, 0x29, 0x72, 0xa2, 0x84, 0x86, 0xdf, 0xd6, 0x60, 0x75, 0x6f, 0x46, 0x32, 0x46, 0xa7,
	0x13, 0xb4, 0x06, 0x36, 0x8d, 0x7d, 0xab, 0x63, 0x75, 0xeb, 0xd8, 0xa6, 0x31, 0x42, 0x50, 0x63,
	0xf3, 0x84, 0xf8, 0xb6, 0x88, 0x88, 0x35, 0xfa, 0x00, 0xed, 0x93, 0x1c, 0xff, 0x91, 0xb2, 0xe3,
	0x77, 0xd1, 0xe4, 0x68, 0x16, 0x1d, 0x11, 0xbf, 0xd6, 0xb1, 0xba, 0x5e, 0x3f, 0xec, 0x45, 0x09,
	0xed, 0x29, 0xc1, 0x62, 0xa1, 0x23, 0x71, 0x25, 0x3f, 0xf8, 0x63, 0x43, 0x73, 0x30, 0xc9, 0xbe,
	0x92, 0x74, 0x37, 0xe1, 0x0f, 0x33, 0xf4, 0x0c, 0xbc, 0x69, 0x42, 0x26, 0xf9, 0x56, 0x5c, 0xcb,
	0xeb, 0xdf, 0x34, 0x0f, 0xd8, 0x5d, 0x00, 0xb0, 0x8e, 0x46, 0x2f, 0xa0, 0x91, 0xd1, 0xc9, 0xd1,
	0x88, 0xc8, 0x80, 0x48, 0xc1, 0xeb, 0x07, 0x26, 0x7b, 0x5f, 0x43, 0x60, 0x03, 0x8f, 0xde, 0x40,
	0x6b, 0x3c, 0x1b, 0x31, 0x9a, 0xa8, 0x48, 0xe6, 0x3b, 0x42, 0xe2, 0xb6, 0x29, 0xf1, 0xde, 0x04,
	0xe1, 0x32, 0x0b, 0x0d, 0xa0, 0x39, 0x8e, 0x58, 0x4a, 0xcf, 0x94, 0x4c, 0xad, 0xe3, 0x74, 0xbd,
	0xfe, 0xad, 0x92, 0x8c, 0x0e, 0xc1, 0x26, 0x83, 0xe7, 0x72, 0x4c, 0x63, 0xa2, 0xc0, 0xbe, 0x2b,
	0x14, 0x4a, 0xb9, 0xbc, 0xd5, 0x10, 0xd8, 0xc0, 0x07, 0x9f, 0xc0, 0xd3, 0xea, 0x84, 0x02, 0x58,
	0x8d, 0x23, 0x16, 0x1d, 0x70, 0x67, 0xa5, 0xd7, 0xc5, 0x1e, 0xdd, 0x01, 0xe0, 0x55, 0x94, 0x46,
	0xe4, 0xbe, 0x6b, 0x11, 0xd4, 0x06, 0x77, 0x44, 0xc7, 0x94, 0x89, 0x62, 0xb8, 0x58, 0x6e, 0x82,
	0x0d, 0x58, 0x51, 0xe2, 0x42, 0x80, 0x2f, 0x0f, 0xc8, 0x19, 0xf3, 0xad, 0x8e, 0x23, 0x05, 0x54,
	0x24, 0xf8, 0x69, 0x41, 0x43, 0x2f, 0x3b, 0x1a, 0xc0, 0xca, 0xb4, 0x70, 0x98, 0xe7, 0x75, 0xef,
	0x62, 0x8f, 0x7a, 0xf9, 0x29, 0xdb, 0x13, 0x96, 0xce, 0xb1, 0xe2, 0xa1, 0x75, 0x58, 0xcb, 0xc8,
	0x88, 0x1c, 0x32, 0x12, 0x6b, 0x6e, 0xd7, 0x71, 0x29, 0x1a, 0xec, 0x41, 0x43, 0x17, 0x40, 0xff,
	0x83, 0xf3, 0x85, 0xcc, 0xf3, 0x1a, 0xf0, 0x25, 0x7a, 0x00, 0xee, 0x69, 0x34, 0x9a, 0x91, 0xbc,
	0x5d, 0x6e, 0x94, 0x9b, 0x4d, 0xda, 0x23, 0x31, 0x4f, 0xed, 0x2d, 0x2b, 0xf8, 0x6d, 0x41, 0xab,
	0xd4, 0x02, 0x68, 0x58, 0xce, 0xe8, 0xfe, 0xd2, 0x96, 0xb9, 0x20, 0xa9, 0x2e, 0xb4, 0xcc, 0xeb,
	0x67, 0xbe, 0x2d, 0xaa, 0x59, 0x0e, 0x5f, 0x47, 0x5a, 0x3f, 0x6c, 0x68, 0x1a, 0x2d, 0x89, 0x9e,
	0x40, 0x8d, 0x29, 0x47, 0xbd, 0xfe, 0xdd, 0x25, 0xdd, 0xdb, 0xe3, 0x3e, 0xcb, 0x64, 0x04, 0x05,
	0xbd, 0x5a, 0xd4, 0xc3, 0x16, 0xec, 0xee, 0x32, 0xf6, 0x55, 0x2d, 0x76, 0x2a, 0x2d, 0x7e, 0x0c,
	0xf5, 0xe2, 0xf8, 0x8a, 0x42, 0xb4, 0xf5, 0x42, 0xd4, 0xf5, 0x8c, 0xaf, 0xa1, 0x88, 0x18, 0x1a,
	0xfa, 0x4b, 0x59, 0x91, 0x83, 0x55, 0x95, 0x03, 0x7f, 0x3f, 0xd5, 0x84, 0xcc, 0xef, 0x59, 0xec,
	0x83, 0x5f, 0x36, 0xb4, 0xab, 0x86, 0x2a, 0x7a, 0x99, 0xfb, 0x23, 0x2b, 0xbc, 0x79, 0xf9, 0x18,
	0x3e, 0x67, 0xd3, 0x6b, 0x70, 0xe9, 0x98, 0x4f, 0x72, 0x47, 0x48, 0x3c, 0xbc, 0x82, 0xc4, 0x0e,
	0xc7, 0x4b, 0x0d, 0xc9, 0xe5, 0xd3, 0x2e, 0xd2, 0x87, 0x78, 0xfe, 0x59, 0x28, 0x4d, 0x3b, 0x63,
	0xce, 0x63, 0x93, 0xf1, 0xef, 0x16, 0x6e, 0x01, 0x2c, 0x2e, 0x74, 0x19, 0xb3, 0xa1, 0x31, 0xc3,
	0x4d, 0x00, 0x75, 0xb7, 0x9d, 0x21, 0x1f, 0x61, 0x27, 0xc5, 0x2e, 0x17, 0xd0, 0x22, 0xe1, 0x3a,
	0xac, 0xee, 0x8b, 0xef, 0xe8, 0xce, 0x90, 0x7b, 0x95, 0xe5, 0x6b, 0x35, 0x4b, 0xd5, 0x3e, 0x7c,
	0x0e, 0x4d, 0xa5, 0x3a, 0x48, 0xd3, 0x88, 0x77, 0x50, 0x5d, 0xc9, 0xa8, 0xd1, 0xd0, 0x34, 0x0a,
	0x83, 0x17, 0xcf, 0xc3, 0x2d, 0xf0, 0xe4, 0x29, 0x92, 0xbb, 0x01, 0x2b, 0x52, 0x58, 0x31, 0x5b,
	0x82, 0x29, 0x21, 0xc3, 0x88, 0x45, 0x58, 0x3d, 0x0f, 0x9b, 0xe0, 0x6d, 0x8f, 0x13, 0x36, 0x97,
	0xcf, 0xc2, 0xef, 0x16, 0xc0, 0x02, 0x76, 0xee, 0x1b, 0xdf, 0x01, 0x2f, 0x26, 0xd9, 0x61, 0x4a,
	0xf5, 0xc9, 0xa9, 0x87, 0x8a, 0xbf, 0x00, 0x47, 0xfb, 0x0b, 0x68, 0x83, 0x9b, 0xb1, 0x59, 0x3c,
	0x17, 0xfe, 0xd6, 0xb1, 0xdc, 0x98, 0x09, 0xba, 0xcb, 0x13, 0xfc, 0xfc, 0x9f, 0xf8, 0x0b, 0x79,
	0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0x43, 0x05, 0x1a, 0x8c, 0x95, 0x08, 0x00, 0x00,
}
