// Code generated by protoc-gen-go. DO NOT EDIT.
// source: survey.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SurveyData struct {
	SurveyID             int64    `protobuf:"varint,1,opt,name=surveyID,proto3" json:"surveyID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurveyData) Reset()         { *m = SurveyData{} }
func (m *SurveyData) String() string { return proto.CompactTextString(m) }
func (*SurveyData) ProtoMessage()    {}
func (*SurveyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0}
}

func (m *SurveyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyData.Unmarshal(m, b)
}
func (m *SurveyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyData.Marshal(b, m, deterministic)
}
func (m *SurveyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyData.Merge(m, src)
}
func (m *SurveyData) XXX_Size() int {
	return xxx_messageInfo_SurveyData.Size(m)
}
func (m *SurveyData) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyData.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyData proto.InternalMessageInfo

func (m *SurveyData) GetSurveyID() int64 {
	if m != nil {
		return m.SurveyID
	}
	return 0
}

func (m *SurveyData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SurveyData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*SurveyData)(nil), "api.SurveyData")
}

func init() { proto.RegisterFile("survey.proto", fileDescriptor_a40f94eaa8e6ca46) }

var fileDescriptor_a40f94eaa8e6ca46 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x2d, 0x2a,
	0x4b, 0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x8a, 0xe3,
	0xe2, 0x0a, 0x06, 0x0b, 0xba, 0x24, 0x96, 0x24, 0x0a, 0x49, 0x71, 0x71, 0x40, 0x94, 0x78, 0xba,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xf9, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05,
	0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x02, 0x17, 0x77, 0x4a, 0x6a,
	0x71, 0x72, 0x51, 0x66, 0x41, 0x49, 0x66, 0x7e, 0x9e, 0x04, 0x33, 0x58, 0x0a, 0x59, 0xc8, 0xc8,
	0x8a, 0x8b, 0x0d, 0x62, 0xbe, 0x90, 0x01, 0x17, 0x8f, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x2a, 0x94,
	0xcf, 0xaf, 0x97, 0x58, 0x90, 0xa9, 0x87, 0xb0, 0x5c, 0x0a, 0x5d, 0x20, 0x89, 0x0d, 0xec, 0x4e,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x73, 0x17, 0x14, 0xb7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SurveyClient is the client API for Survey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SurveyClient interface {
	CreateSurvey(ctx context.Context, in *SurveyData, opts ...grpc.CallOption) (*SurveyData, error)
}

type surveyClient struct {
	cc *grpc.ClientConn
}

func NewSurveyClient(cc *grpc.ClientConn) SurveyClient {
	return &surveyClient{cc}
}

func (c *surveyClient) CreateSurvey(ctx context.Context, in *SurveyData, opts ...grpc.CallOption) (*SurveyData, error) {
	out := new(SurveyData)
	err := c.cc.Invoke(ctx, "/api.Survey/CreateSurvey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurveyServer is the server API for Survey service.
type SurveyServer interface {
	CreateSurvey(context.Context, *SurveyData) (*SurveyData, error)
}

// UnimplementedSurveyServer can be embedded to have forward compatible implementations.
type UnimplementedSurveyServer struct {
}

func (*UnimplementedSurveyServer) CreateSurvey(ctx context.Context, req *SurveyData) (*SurveyData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSurvey not implemented")
}

func RegisterSurveyServer(s *grpc.Server, srv SurveyServer) {
	s.RegisterService(&_Survey_serviceDesc, srv)
}

func _Survey_CreateSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SurveyData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServer).CreateSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Survey/CreateSurvey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServer).CreateSurvey(ctx, req.(*SurveyData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Survey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Survey",
	HandlerType: (*SurveyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSurvey",
			Handler:    _Survey_CreateSurvey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "survey.proto",
}
