// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trigger.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatedTrigger struct {
	Condition            []string  `protobuf:"bytes,1,rep,name=condition,proto3" json:"condition,omitempty"`
	Action               []*Action `protobuf:"bytes,2,rep,name=action,proto3" json:"action,omitempty"`
	StudyID              string    `protobuf:"bytes,3,opt,name=studyID,proto3" json:"studyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatedTrigger) Reset()         { *m = CreatedTrigger{} }
func (m *CreatedTrigger) String() string { return proto.CompactTextString(m) }
func (*CreatedTrigger) ProtoMessage()    {}
func (*CreatedTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{0}
}

func (m *CreatedTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedTrigger.Unmarshal(m, b)
}
func (m *CreatedTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedTrigger.Marshal(b, m, deterministic)
}
func (m *CreatedTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedTrigger.Merge(m, src)
}
func (m *CreatedTrigger) XXX_Size() int {
	return xxx_messageInfo_CreatedTrigger.Size(m)
}
func (m *CreatedTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedTrigger proto.InternalMessageInfo

func (m *CreatedTrigger) GetCondition() []string {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *CreatedTrigger) GetAction() []*Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *CreatedTrigger) GetStudyID() string {
	if m != nil {
		return m.StudyID
	}
	return ""
}

type Condition struct {
	Condition            []string `protobuf:"bytes,1,rep,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{1}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetCondition() []string {
	if m != nil {
		return m.Condition
	}
	return nil
}

type Action struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{2}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Action) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Attributes struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sick                 string   `protobuf:"bytes,4,opt,name=sick,proto3" json:"sick,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attributes) Reset()         { *m = Attributes{} }
func (m *Attributes) String() string { return proto.CompactTextString(m) }
func (*Attributes) ProtoMessage()    {}
func (*Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{3}
}

func (m *Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attributes.Unmarshal(m, b)
}
func (m *Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attributes.Marshal(b, m, deterministic)
}
func (m *Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attributes.Merge(m, src)
}
func (m *Attributes) XXX_Size() int {
	return xxx_messageInfo_Attributes.Size(m)
}
func (m *Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_Attributes proto.InternalMessageInfo

func (m *Attributes) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Attributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attributes) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Attributes) GetSick() string {
	if m != nil {
		return m.Sick
	}
	return ""
}

func (m *Attributes) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*CreatedTrigger)(nil), "api.CreatedTrigger")
	proto.RegisterType((*Condition)(nil), "api.Condition")
	proto.RegisterType((*Action)(nil), "api.Action")
	proto.RegisterType((*Attributes)(nil), "api.Attributes")
}

func init() { proto.RegisterFile("trigger.proto", fileDescriptor_8c31e6d8b4368946) }

var fileDescriptor_8c31e6d8b4368946 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4e, 0x83, 0x40,
	0x14, 0x2c, 0xa5, 0xa5, 0xe1, 0xd5, 0xaa, 0x59, 0x8d, 0xd9, 0x34, 0x1e, 0xc8, 0x7a, 0xc1, 0x0b,
	0x69, 0xf0, 0xe8, 0xa9, 0xa1, 0x97, 0x5e, 0x89, 0x3f, 0xb0, 0x85, 0x0d, 0xdd, 0xd4, 0x02, 0x59,
	0x1e, 0xd5, 0xfe, 0xbd, 0xe1, 0x2d, 0x54, 0x4d, 0x8c, 0xb7, 0x99, 0x79, 0x6f, 0x66, 0x77, 0x67,
	0x61, 0x81, 0x46, 0x17, 0x85, 0x32, 0x51, 0x6d, 0x2a, 0xac, 0x98, 0x2b, 0x6b, 0x2d, 0x8e, 0x70,
	0x9d, 0x18, 0x25, 0x51, 0xe5, 0x6f, 0x76, 0xc8, 0x1e, 0xc1, 0xcf, 0xaa, 0x32, 0xd7, 0xa8, 0xab,
	0x92, 0x3b, 0x81, 0x1b, 0xfa, 0xe9, 0xb7, 0xc0, 0x9e, 0xc0, 0x93, 0x19, 0x8d, 0xc6, 0x81, 0x1b,
	0xce, 0xe3, 0x79, 0x24, 0x6b, 0x1d, 0xad, 0x49, 0x4a, 0xfb, 0x11, 0xe3, 0x30, 0x6b, 0xb0, 0xcd,
	0xcf, 0xdb, 0x0d, 0x77, 0x03, 0x27, 0xf4, 0xd3, 0x81, 0x8a, 0x67, 0xf0, 0x93, 0x4b, 0xd6, 0xbf,
	0x27, 0x89, 0x18, 0x3c, 0x1b, 0xcb, 0x18, 0x4c, 0xf0, 0x5c, 0x2b, 0xee, 0x50, 0x16, 0x61, 0x76,
	0x0f, 0xd3, 0x93, 0x7c, 0x6f, 0x15, 0x1f, 0x93, 0x68, 0x89, 0x38, 0x01, 0xac, 0x11, 0x8d, 0xde,
	0xb5, 0xa8, 0x1a, 0xf6, 0x00, 0x5e, 0xdb, 0x28, 0xb3, 0xdd, 0xf4, 0xce, 0x9e, 0x75, 0x79, 0xa5,
	0x3c, 0x0e, 0x56, 0xc2, 0xec, 0x16, 0x5c, 0x59, 0x28, 0xba, 0xee, 0x34, 0xed, 0x60, 0xb7, 0xd5,
	0xe8, 0xec, 0xc0, 0x27, 0x76, 0xab, 0xc3, 0x5d, 0xe2, 0x87, 0xd2, 0xc5, 0x1e, 0xf9, 0x94, 0x16,
	0x7b, 0x16, 0x7f, 0xc2, 0x6c, 0xa8, 0xef, 0x15, 0x16, 0xb6, 0xd0, 0x41, 0xb8, 0xa3, 0x86, 0x7e,
	0x97, 0xbc, 0xfc, 0x4b, 0x14, 0x23, 0xb6, 0x82, 0xab, 0x64, 0xaf, 0xb2, 0xc3, 0xe0, 0xbd, 0xb1,
	0xed, 0x5e, 0x9e, 0xb4, 0xfc, 0x59, 0xb7, 0x18, 0xad, 0x9c, 0x9d, 0x47, 0x7f, 0xf9, 0xf2, 0x15,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0x28, 0x67, 0x26, 0xdc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TriggerClient is the client API for Trigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TriggerClient interface {
	CreateTrigger(ctx context.Context, in *CreatedTrigger, opts ...grpc.CallOption) (*CreatedTrigger, error)
	CheckTrigger(ctx context.Context, in *Attributes, opts ...grpc.CallOption) (Trigger_CheckTriggerClient, error)
}

type triggerClient struct {
	cc *grpc.ClientConn
}

func NewTriggerClient(cc *grpc.ClientConn) TriggerClient {
	return &triggerClient{cc}
}

func (c *triggerClient) CreateTrigger(ctx context.Context, in *CreatedTrigger, opts ...grpc.CallOption) (*CreatedTrigger, error) {
	out := new(CreatedTrigger)
	err := c.cc.Invoke(ctx, "/api.Trigger/CreateTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerClient) CheckTrigger(ctx context.Context, in *Attributes, opts ...grpc.CallOption) (Trigger_CheckTriggerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Trigger_serviceDesc.Streams[0], "/api.Trigger/CheckTrigger", opts...)
	if err != nil {
		return nil, err
	}
	x := &triggerCheckTriggerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Trigger_CheckTriggerClient interface {
	Recv() (*Action, error)
	grpc.ClientStream
}

type triggerCheckTriggerClient struct {
	grpc.ClientStream
}

func (x *triggerCheckTriggerClient) Recv() (*Action, error) {
	m := new(Action)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TriggerServer is the server API for Trigger service.
type TriggerServer interface {
	CreateTrigger(context.Context, *CreatedTrigger) (*CreatedTrigger, error)
	CheckTrigger(*Attributes, Trigger_CheckTriggerServer) error
}

// UnimplementedTriggerServer can be embedded to have forward compatible implementations.
type UnimplementedTriggerServer struct {
}

func (*UnimplementedTriggerServer) CreateTrigger(ctx context.Context, req *CreatedTrigger) (*CreatedTrigger, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrigger not implemented")
}
func (*UnimplementedTriggerServer) CheckTrigger(req *Attributes, srv Trigger_CheckTriggerServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckTrigger not implemented")
}

func RegisterTriggerServer(s *grpc.Server, srv TriggerServer) {
	s.RegisterService(&_Trigger_serviceDesc, srv)
}

func _Trigger_CreateTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatedTrigger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServer).CreateTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Trigger/CreateTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServer).CreateTrigger(ctx, req.(*CreatedTrigger))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trigger_CheckTrigger_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Attributes)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TriggerServer).CheckTrigger(m, &triggerCheckTriggerServer{stream})
}

type Trigger_CheckTriggerServer interface {
	Send(*Action) error
	grpc.ServerStream
}

type triggerCheckTriggerServer struct {
	grpc.ServerStream
}

func (x *triggerCheckTriggerServer) Send(m *Action) error {
	return x.ServerStream.SendMsg(m)
}

var _Trigger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Trigger",
	HandlerType: (*TriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrigger",
			Handler:    _Trigger_CreateTrigger_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckTrigger",
			Handler:       _Trigger_CheckTrigger_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trigger.proto",
}
