// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMetaData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TimeLastAssigned     int64    `protobuf:"varint,2,opt,name=timeLastAssigned,proto3" json:"timeLastAssigned,omitempty"`
	TimeToSend           int64    `protobuf:"varint,3,opt,name=timeToSend,proto3" json:"timeToSend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMetaData) Reset()         { *m = UserMetaData{} }
func (m *UserMetaData) String() string { return proto.CompactTextString(m) }
func (*UserMetaData) ProtoMessage()    {}
func (*UserMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMetaData.Unmarshal(m, b)
}
func (m *UserMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMetaData.Marshal(b, m, deterministic)
}
func (m *UserMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMetaData.Merge(m, src)
}
func (m *UserMetaData) XXX_Size() int {
	return xxx_messageInfo_UserMetaData.Size(m)
}
func (m *UserMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_UserMetaData proto.InternalMessageInfo

func (m *UserMetaData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserMetaData) GetTimeLastAssigned() int64 {
	if m != nil {
		return m.TimeLastAssigned
	}
	return 0
}

func (m *UserMetaData) GetTimeToSend() int64 {
	if m != nil {
		return m.TimeToSend
	}
	return 0
}

func init() {
	proto.RegisterType((*UserMetaData)(nil), "api.UserMetaData")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x2a, 0xe2, 0xe2, 0x09,
	0x2d, 0x4e, 0x2d, 0xf2, 0x4d, 0x2d, 0x49, 0x74, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe3, 0x62, 0x03,
	0x29, 0xf1, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0xb4, 0xb8, 0x04,
	0x4a, 0x32, 0x73, 0x53, 0x7d, 0x12, 0x8b, 0x4b, 0x1c, 0x8b, 0x8b, 0x33, 0xd3, 0xf3, 0x52, 0x53,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x30, 0xc4, 0x85, 0xe4, 0xb8, 0xb8, 0x40, 0x62, 0x21,
	0xf9, 0xc1, 0xa9, 0x79, 0x29, 0x12, 0xcc, 0x60, 0x55, 0x48, 0x22, 0x46, 0x56, 0x5c, 0x2c, 0x20,
	0x3b, 0x85, 0x8c, 0xb8, 0xb8, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0xc1, 0x3c, 0x41, 0xbd, 0xc4,
	0x82, 0x4c, 0x3d, 0x64, 0xc7, 0x48, 0x61, 0x0a, 0x25, 0xb1, 0x81, 0xdd, 0x6e, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0x24, 0xb2, 0xae, 0xc9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	CreateUser(ctx context.Context, in *UserMetaData, opts ...grpc.CallOption) (*UserMetaData, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) CreateUser(ctx context.Context, in *UserMetaData, opts ...grpc.CallOption) (*UserMetaData, error) {
	out := new(UserMetaData)
	err := c.cc.Invoke(ctx, "/api.User/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	CreateUser(context.Context, *UserMetaData) (*UserMetaData, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) CreateUser(ctx context.Context, req *UserMetaData) (*UserMetaData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMetaData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*UserMetaData))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
