// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attributes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Sick                 string   `protobuf:"bytes,3,opt,name=sick,proto3" json:"sick,omitempty"`
	Weight               int32    `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attributes) Reset()         { *m = Attributes{} }
func (m *Attributes) String() string { return proto.CompactTextString(m) }
func (*Attributes) ProtoMessage()    {}
func (*Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attributes.Unmarshal(m, b)
}
func (m *Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attributes.Marshal(b, m, deterministic)
}
func (m *Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attributes.Merge(m, src)
}
func (m *Attributes) XXX_Size() int {
	return xxx_messageInfo_Attributes.Size(m)
}
func (m *Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_Attributes proto.InternalMessageInfo

func (m *Attributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attributes) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Attributes) GetSick() string {
	if m != nil {
		return m.Sick
	}
	return ""
}

func (m *Attributes) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*Attributes)(nil), "api.Attributes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x8a, 0xe3, 0xe2, 0x72,
	0x2c, 0x29, 0x29, 0xca, 0x4c, 0x2a, 0x2d, 0x49, 0x2d, 0x16, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x13, 0xd3,
	0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x40, 0x4c, 0x90, 0xaa, 0xe2, 0xcc, 0xe4, 0x6c,
	0x09, 0x66, 0x88, 0x2a, 0x10, 0x5b, 0x48, 0x8c, 0x8b, 0xad, 0x3c, 0x35, 0x33, 0x3d, 0xa3, 0x44,
	0x82, 0x05, 0xac, 0x10, 0xca, 0x33, 0x32, 0xe5, 0x62, 0x77, 0x4f, 0x2d, 0x09, 0x2d, 0x4e, 0x2d,
	0x12, 0xd2, 0xe2, 0x62, 0x01, 0xd3, 0xfc, 0x7a, 0x89, 0x05, 0x99, 0x7a, 0x08, 0x5b, 0xa5, 0xd0,
	0x05, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x4e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x04, 0xea,
	0xa9, 0x6d, 0xb0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetUserClient is the client API for GetUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetUserClient interface {
	User(ctx context.Context, in *Attributes, opts ...grpc.CallOption) (*Attributes, error)
}

type getUserClient struct {
	cc *grpc.ClientConn
}

func NewGetUserClient(cc *grpc.ClientConn) GetUserClient {
	return &getUserClient{cc}
}

func (c *getUserClient) User(ctx context.Context, in *Attributes, opts ...grpc.CallOption) (*Attributes, error) {
	out := new(Attributes)
	err := c.cc.Invoke(ctx, "/api.GetUser/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserServer is the server API for GetUser service.
type GetUserServer interface {
	User(context.Context, *Attributes) (*Attributes, error)
}

// UnimplementedGetUserServer can be embedded to have forward compatible implementations.
type UnimplementedGetUserServer struct {
}

func (*UnimplementedGetUserServer) User(ctx context.Context, req *Attributes) (*Attributes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}

func RegisterGetUserServer(s *grpc.Server, srv GetUserServer) {
	s.RegisterService(&_GetUser_serviceDesc, srv)
}

func _GetUser_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attributes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GetUser/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserServer).User(ctx, req.(*Attributes))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GetUser",
	HandlerType: (*GetUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "User",
			Handler:    _GetUser_User_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
